[package]
name = "poc_tests"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
fehler = "1.0.0"
anchor-spl = "0.28.0"
[dev-dependencies.trdelnik-client]
path = "../../../../crates/client"
features = ["poctesting"]

[dev-dependencies.program_client]
path = "../../.program_client"

[dev-dependencies.escrow]
path = "../../programs/escrow"
