[package]
name = "program_client"
version = "0.1.0"
edition = "2018"
[dependencies.trdelnik-client]
path = "../../../crates/client"

[dependencies.escrow]
path = "../programs/escrow"
features = ["no-entrypoint"]
