[package]
name = "trdelnik-client"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/Ackee-Blockchain/trdelnik"
license-file = "../../LICENSE"
readme = "../../README.md"
description = "The trdelnik_client crate helps you build and deploy an Anchor program to a local cluster and run a test suite against it."

[features]
fuzzing = [
    "dep:solana-program-test",
    "dep:honggfuzz",
    "arbitrary/derive",
    "quinn-proto/arbitrary",
]
poctesting = ["dep:rstest", "dep:serial_test", "dep:trdelnik-test"]
[build-dependencies]
anyhow = { version = "1.0.45", features = ["std"], default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"

[dependencies]
solana-sdk = { workspace = true }
solana-cli-output = { workspace = true }
solana-transaction-status = { workspace = true }
solana-account-decoder = { workspace = true }
anchor-client = { workspace = true }
anchor-lang = { version = "0.28.0" }
spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
futures = { workspace = true }
fehler = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
heck = { workspace = true }
toml = { workspace = true }
log = { workspace = true }

trdelnik-test = { workspace = true, optional = true }
serial_test = { version = "2.0.0", optional = true }
rstest = { version = "0.18.2", optional = true }
honggfuzz = { version = "0.5.55", optional = true }
arbitrary = { version = "1.3.0", optional = true }
solana-program-test = { version = "1.16.9", optional = true }
quinn-proto = { version = "0.9.4", optional = true }
shellexpand = { workspace = true }
pathdiff = "0.2.1"
indicatif = "0.17.7"
