[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "5WfCwQJCCNTbHwQsXKt1hYZpmbYLGidM3hehap8tk6gc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
