[features]
seeds = false
skip-lint = false
[programs.localnet]
fuzzer_with_token = "BY6vsKLyMNhcSLEhaD4iUc2B49PjQ7wkqB4CeoT4eca2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
