[package]
name = "poc_tests"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
assert_matches = "1.4.0"
fehler = "1.0.0"
rstest = "0.12.0"

[dev-dependencies.trdelnik-client]
path = "../../../../crates/client"

[dev-dependencies.program_client]
path = "../../.program_client"

[dev-dependencies.turnstile]
path = "../../programs/turnstile"
