[package]
name = "trdelnik-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-cli-config = "1.10.0"
solana-client = "1.10.0"
solana-sdk = "1.10.0"
solana-logger = "1.10.0"
thiserror = "1.0.30"
serde = "1.0.136"
serde_json = "1.0.79"
base64 = "0.13.0"
pretty-hex = "0.2.1"
console = "0.15.0"
