[package]
name = "trdelnik-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-cli-config = "1.10.3"
solana-client = "1.10.3"
solana-sdk = "1.10.3"
solana-logger = "1.10.3"
solana-transaction-status = "1.10.3"
solana-vote-program = "1.10.3"
spl-memo = "3.0.1"
thiserror = "1.0.30"
serde = "1.0.136"
serde_json = "1.0.79"
base64 = "0.13.0"
pretty-hex = "0.2.1"
console = "0.15.0"
chrono = "0.4.19"
