[package]
name = "program_client"
version = "0.1.0"
edition = "2018"

[dependencies.trdelnik-client]
path = "../../../crates/client"


[dependencies.fuzz_example3]
path = "../programs/fuzz_example3"
features = ["no-entrypoint"]
