[package]
name = "poc_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"
[dev-dependencies.trident-client]
path = "../../../../crates/client"


[dev-dependencies.program_client]
path = "../../.program_client"

[dependencies]
assert_matches = "1.4.0"
fehler = "1.0.0"
rstest = "0.12.0"

[dependencies.fuzz_example0]
path = "../../programs/fuzz_example0"
