[package]
name = "turnstile"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "turnstile"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.24.2"

[dev-dependencies]
fehler = "1.0.0"
trdelnik-client = { path = "../../../../crates/client" }
program_client = { path = "../../program_client" }
rstest = "0.12.0"
