[package]
name = "trdelnik_program"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trdelnik_program_macros = { path = "../trdelnik_program_macros" }
anchor-lang = "0.18.0"
