[package]
name = "program_client"
version = "0.1.0"
edition = "2018"
[dependencies.trdelnik]
path = "../../../crates/trdelnik"

[dependencies.turnstile]
path = "../programs/turnstile"
features = ["no-entrypoint"]
