[package]
name = "program_client"
version = "0.1.0"
edition = "2018"

[dependencies.trident-client]
path = "../../../crates/client"

[dependencies.fuzz_example0]
path = "../programs/fuzz_example0"
features = ["no-entrypoint"]
