[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fuzz_example5 = "9UhXSCF8KxxhsFubWGig88FgmvnxkV4jwB87D7RjRE7v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
