on:
  pull_request:
  push:
    branches: [master]

name: Lint crates

jobs:
  checks:
    runs-on: ubuntu-20.04
    needs:
      - explorer
      - cli
      - client
      - test
    steps:
      - run: echo "Done"

  explorer:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: crates/explorer
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: actions/cache@v3
        name: Cache Rust and it's packages
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ runner.os }}-v0000-${{ steps.rust-setup.outputs.rustc-hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: cargo build
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
      - name: Cargo test
        run: cargo test

  cli:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: crates/cli
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: actions/cache@v3
        name: Cache Rust and it's packages
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ runner.os }}-v0000-${{ steps.rust-setup.outputs.rustc-hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: cargo build
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
      - name: Cargo test
        run: cargo test

  client:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: crates/client
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: actions/cache@v3
        name: Cache Rust and it's packages
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ runner.os }}-v0000-${{ steps.rust-setup.outputs.rustc-hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: cargo build
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
      - name: Cargo test
        run: cargo test

  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: crates/test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: actions/cache@v3
        id: cargo-cache
        name: Cache Rust and it's packages
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ runner.os }}-v0000-${{ steps.rust-setup.outputs.rustc-hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo packages
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-expand
      - name: Cargo build
        run: cargo build
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
      - name: Cargo test
        run: cargo test
