on:
  pull_request:
  push:
    branches: [master]

name: Test examples/turnstile

env:
  SOLANA_CLI_VERSION: 1.10.8

jobs:
  turnstile:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: examples/turnstile
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-rust/
        id: rust-setup
      - uses: actions/cache@v3
        id: cargo-cache
        name: Cache Rust and it's packages
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ runner.os }}-v0000-${{ steps.rust-setup.outputs.rustc-hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo packages
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-expand
          cargo install --force cargo-make
      - name: Cargo build
        run: cargo build
      - name: Prepare program client
        run: makers trdelnik build
      - name: Run trdelnik test
        run: makers trdelnik test
